dubbo:
  application:
    name: provider1
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20881

server:
  port: 8083
spring:
  profiles:
    include: db,mapper
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: user.add.exchange
    publisher-confirms: true

