
dubbo:
  consumer:
    check: false
  application:
    name: provider
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880

server:
  port: 8081
spring:
  profiles:
    include: db,mapper